name: Add Reviewer to Dependabot PRs

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
        description: Token to run the workflow
  pull_request:
    types: [opened]

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Add Reviewer
        run: gh pr edit "$PR_NUMBER" --add-reviewer "$REVIEWER"
    env:
      PR_NUMBER: ${{ github.event.number }}
      # gh cli require GH_TOKEN variable
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REVIEWER: ${{ github.repository_owner }}
    