name: Add Reviewer to Dependabot PRs

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
        description: Token to run the workflow
  pull_request:
    types: [opened, synchronize]

jobs:
  add-reviewer-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Add Reviewer
        run: gh pr edit "$PR_NUMBER" --add-reviewer "$REVIEWER"
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_TOKEN: ${{ github.token }}
      REVIEWER: ${{ github.repository_owner }}

  add-reviewer-wf:
    if: github.event_name == 'workflow_call' && github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6
      - name: Add Reviewer
        run: gh pr edit "$PR_NUMBER" --add-reviewer "$REVIEWER"
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REVIEWER: ${{ github.repository_owner }}
