name: Auto merge dependabot pull requests
# Dependabotが作成したPRのうち、GitHub Actionsの更新またはパッチバージョンの更新を自動でマージする

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
        description: Token to run the workflow
  pull_request:
    types: [opened]

jobs:
  automerge:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2 ## dependabotの更新内容を取得（https://github.com/dependabot/fetch-metadata）
      - name: Auto approve and merge
        if: ${{ steps.meta.outputs.package-ecosystem == 'github_actions' || steps.meta.outputs.update-type != 'version-update:semver-major' }}
        run: |
          # リポジトリ設定のAllow GitHub Actions to create and approve pull requestsを有効にしておく必要あり
          gh pr review ${{ github.event.number }} --approve
          # autoフラグはリポジトリ設定のAllow auto-mergeを有効にしておく必要あり
          gh pr merge ${{ github.event.number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}