name: Secret scan

on:
  workflow_call

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: secret lint
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          secretlint/secretlint secretlint --maskSecrets '**/*'